lab crud
codechipceo/cc-06-researchdecode-dashboard pull request #2
Opened 2024-09-27 12:44 UTC by nayabshah

2024-10-03 12:44 UTC, codechipceo commented on src/Components/FormComponent/FormComponent.jsx
> +
Why have you removed these things that are being use on other pages??

2024-10-03 12:46 UTC, codechipceo commented on src/Components/FormComponent/FormComponent.jsx
> -        <Button onClick={() => onCancel()}>Cancel</Button>
same for this? This not unnecessary code written here, do not remove existing code when you are implementing changes in some existing codes. It might break entire project
![{52C8516C-0D35-4058-B564-5917A8CD3EBE}](https://github.com/user-attachments/assets/3375fc8d-4aa0-48a0-acb9-90b1be8b6c19)

2024-10-03 12:47 UTC, codechipceo requested changes
Please fix these issues so i can merge

2024-10-03 13:45 UTC, nayabshah commented on src/Components/FormComponent/FormComponent.jsx
> -        <Button onClick={() => onCancel()}>Cancel</Button>
bro i didn't work in that

2024-10-07 10:01 UTC, codechipceo approved these changes

2024-10-07 10:01 UTC, merged